### ISSUE TITLE
project with no source files leads to `type not supported: <nil>` panic + stack trace

### ISSUE THREAD

**Issue by symbiont-chris-vogt** [bazelbuild/bazel-gazelle#1098]
### What version of gazelle are you using?

v0.23.0 / 62ca106be173579c0a167deb23358fdfe71ffa1e4cfdddf5582af26520f1c66f

### What version of rules_go are you using?

v0.27.0 / 69de5c704a05ff37862f7e0f5534d4f479418afc21806c887db544a316f3cb6b

also tried 0.28

### What version of Bazel are you using?

4.1.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

macos intel

### What did you do?

run gazelle on a haskell project with no .hs source files

### What did you expect to see?

bazel files being produced

### What did you see instead?

panic with stack trace 

```
gazelle: type not supported: <nil>
panic: type not supported: <nil>

goroutine 1 [running]:
log.Panicf(0x163847e, 0x16, 0xc000d2c448, 0x1, 0x1)
	GOROOT/src/log/log.go:361 +0xc5
github.com/bazelbuild/bazel-gazelle/rule.ExprFromValue(0x0, 0x0, 0x0, 0x0)
	external/bazel_gazelle/rule/value.go:163 +0x405
github.com/bazelbuild/bazel-gazelle/rule.(*Rule).SetAttr(0xc000aea080, 0xc000ec2008, 0x4, 0x0, 0x0)
	external/bazel_gazelle/rule/rule.go:825 +0x3c
github.com/bazelbuild/bazel-gazelle/rule.MergeRules(0xc000b14080, 0xc000aea080, 0xc0003f6480, 0xc000ac6320, 0x46)
	external/bazel_gazelle/rule/merge.go:76 +0x65d
github.com/bazelbuild/bazel-gazelle/merger.MergeFile(0xc000ae6460, 0x0, 0x0, 0x0, 0xc000138038, 0x1, 0x1, 0x0, 0xc000d2d9a0)
	external/bazel_gazelle/merger/merger.go:172 +0xb1e
main.runFixUpdate.func1(0xc000a9c8c0, 0x3a, 0xc000a78948, 0x15, 0xc0008a0000, 0xc000ab7201, 0xc000ae6460, 0x0, 0x0, 0x0, ...)
	external/bazel_gazelle/cmd/gazelle/fix-update.go:340 +0x116d
github.com/bazelbuild/bazel-gazelle/walk.Walk.func1(0xc000c6af20, 0xc000a9c8c0, 0x3a, 0xc000a78948, 0x15, 0xc000cbc601)
	external/bazel_gazelle/walk/walk.go:174 +0x6e5
github.com/bazelbuild/bazel-gazelle/walk.Walk.func1(0xc000c6ab00, 0xc000c9b300, 0x31, 0xc00069c930, 0xc, 0xc000d51c01)
	external/bazel_gazelle/walk/walk.go:167 +0x89f
github.com/bazelbuild/bazel-gazelle/walk.Walk.func1(0xc0001584d0, 0xc000c72c60, 0x28, 0xc00069c62c, 0x3, 0xc0005ac401)
	external/bazel_gazelle/walk/walk.go:167 +0x89f
github.com/bazelbuild/bazel-gazelle/walk.Walk.func1(0xc0001584d0, 0xc000162450, 0x24, 0x0, 0x0, 0xc000275000)
	external/bazel_gazelle/walk/walk.go:167 +0x89f
github.com/bazelbuild/bazel-gazelle/walk.Walk(0xc0001584d0, 0xc0003fc000, 0x7, 0xc, 0xc000121c90, 0x1, 0x1, 0x0, 0xc00066d978)
	external/bazel_gazelle/walk/walk.go:177 +0x2a2
main.runFixUpdate(0xc0000260da, 0x24, 0x0, 0xc000110060, 0x2, 0x2, 0x0, 0x0)
	external/bazel_gazelle/cmd/gazelle/fix-update.go:275 +0xae7
main.run(0xc0000260da, 0x24, 0xc000110050, 0x3, 0x3, 0xc000000180, 0xc00027ff78)
	external/bazel_gazelle/cmd/gazelle/gazelle.go:95 +0x1f5
main.main()
	external/bazel_gazelle/cmd/gazelle/gazelle.go:72 +0xe6
```

**Comment by robfig** [comment]
Thanks for the bug report. I agree that this is a bug, but given the extremely limited development bandwidth available combined with the low impact of this issue, I would be inclined to close as "will not fix", unless you'd like to submit a PR.
