### ISSUE TITLE
v0.26.0: error running update-repos

### ISSUE THREAD

**Issue by noahdietz** [bazelbuild/bazel-gazelle#1285]
### What version of gazelle are you using?

v0.26.0

### What version of rules_go are you using?

v0.33.0

### What version of Bazel are you using?

5.0.0

### What operating system and processor architecture are you using?

Ubuntu/Linux x86_64

### What did you do?

In the repository github.com/googleapis/gapic-generator-go, our CI updates the bazel repositories when the go.mod/go.sum changes with the following command:

```
bazel run //:gazelle -- update-repos -from_file=go.mod -prune -to_macro=repositories.bzl%com_googleapis_gapic_generator_go_repositories
```

### What did you expect to see?

My macro updated with the latest changes to my go.mod/go.sum.

### What did you see instead?

```
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_ndietz/a540e4979ce078b5ff3ea0f13b5e6fa8/external/bazel_gazelle/internal/BUILD.bazel", line 19, column 26, in <toplevel>
                gazelle_binary_test_suite()
        File "/private/var/tmp/_bazel_ndietz/a540e4979ce078b5ff3ea0f13b5e6fa8/external/bazel_gazelle/internal/gazelle_binary_test.bzl", line 27, column 19, in gazelle_binary_test_suite
                unittest.suite(
        File "/private/var/tmp/_bazel_ndietz/a540e4979ce078b5ff3ea0f13b5e6fa8/external/bazel_skylib/lib/unittest.bzl", line 270, column 18, in _suite
                test_rule(name = test_name)
Error: 'struct' object is not callable
ERROR: /Users/ndietz/Documents/mod/gapic-generator-go/BUILD:4:8: every rule of type _gazelle_runner implicitly depends upon the target '@bazel_gazelle//internal:gazelle.bash.in', but this target could not be found because of: no such target '@bazel_gazelle//internal:gazelle.bash.in': target 'gazelle.bash.in' not declared in package 'internal'; however, a source file of this name exists.  (Perhaps add 'exports_files(["gazelle.bash.in"])' to internal/BUILD?) defined by /private/var/tmp/_bazel_ndietz/a540e4979ce078b5ff3ea0f13b5e6fa8/external/bazel_gazelle/internal/BUILD.bazel
ERROR: Analysis of target '//:gazelle' failed; build aborted: 
INFO: Elapsed time: 30.536s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (39 packages loaded, 385 targets configured)
FAILED: Build did NOT complete successfully (39 packages loaded, 385 targets configured)
    Fetching @local_config_cc; Restarting.
```

**Comment by sessfeld** [comment]
For me, this was related to [bazel-skylib](https://github.com/bazelbuild/bazel-skylib). Something in my workspace I before `gazelle_dependencies()` was pulling in an older version than the one Gazelle uses. After I added a never version further up in my workspace it works.

**Comment by noahdietz** [comment]
> For me, this was related to [bazel-skylib](https://github.com/bazelbuild/bazel-skylib). Something in my workspace I before `gazelle_dependencies()` was pulling in an older version than the one Gazelle uses. After I added a never version further up in my workspace it works.

Thank you @sessfeld that also fixed things for me. I included the latest version of `bazel-skylib` (v1.2.1 as of writing this) in my WORKSPACE (where I did not previously have it specified) and execution of `update-repos` works now.

**Comment by sabeer6870** [comment]
>Something in my workspace I before gazelle_dependencies() was pulling in an older version than the one Gazelle uses

@sessfeld I am interested in knowing how you come to that conclusion. Can you please share, this might help me in figuring out other issues as well.
