### ISSUE TITLE
gazelle_dependencies fails during `Repository bazel_gazelle_go_repository_config instantiated` when modern rules_pkg is used.

### ISSUE THREAD

**Issue by kurt-google** [bazelbuild/bazel-gazelle#1320]
### What version of gazelle are you using?

```
http_archive(
    name = "bazel_gazelle",
    sha256 = "501deb3d5695ab658e82f6f6f549ba681ea3ca2a5fb7911154b5aa45596183fa",
    urls = [ 
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.26.0/bazel-gazelle-v0.26.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.26.0/bazel-gazelle-v0.26.0.tar.gz",    ],
)
```

### What version of rules_go are you using?

```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "685052b498b6ddfe562ca7a97736741d87916fe536623afb7da2824c0211c369",
    urls = [ 
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.33.0/rules_go-v0.33.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.33.0/rules_go-v0.33.0.zip",
    ],  
)
```

### What version of Bazel are you using?

5.2.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux, x64

### What did you do?

Attempt to update rules_pkg to 0.7.0, observe that gazelle fails during analysis step.

### What did you expect to see?

Builds continue to build successfully.

### What did you see instead?

```
$ bazel build ...                                                       
INFO: Repository bazel_gazelle_go_repository_config instantiated at:                   
  /tmp/WORKSPACE:54:21: in <toplevel>        
  /tmp/.cache/bazel/_bazel_kkartaltepe/62c83de91065532a5cdf2570765dcf7c/external/bazel_gazelle/deps.bzl:80:25: in gazelle_dependencies 
Repository rule go_repository_config defined at: /tmp/.cache/bazel/_bazel_kkartaltepe/62c83de91065532a5cdf2570765dcf7c/external/bazel_gazelle/internal/go_repository_config.bzl:62:39: in <toplevel>                                       
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_config':
   Traceback (most recent call last):
        File "/tmp/.cache/bazel/_bazel_kkartaltepe/62c83de91065532a5cdf2570765dcf7c/external/bazel_gazelle/internal/go_repository_config.bzl", line 40, column 17, in _go_repository_config_impl                                                                                                         
                fail("generate_repo_config: " + result.stderr)
Error in fail: generate_repo_config: generate_repo_config: /tmp/WORKSPACE: multiple rules have the name "rules_pkg"                                                             
ERROR: /tmp/WORKSPACE:54:21: fetching go_repository_config rule //external:bazel_gazelle_go_repository_config: Traceback (most recent call last):
        File "/tmp/.cache/bazel/_bazel_kkartaltepe/62c83de91065532a5cdf2570765dcf7c/external/bazel_gazelle/internal/go_repository_config.bzl", line 40, column 17, in _go_repository_config_impl
                fail("generate_repo_config: " + result.stderr)
Error in fail: generate_repo_config: generate_repo_config: /tmp/WORKSPACE: multiple rules have the name "rules_pkg"
ERROR: /tmp/BUILD.bazel:13:6: no such package '@io_k8s_sigs_kustomize_kustomize_v4//': no such package '@bazel_gazelle_go_repository_config//': generate_repo_config: generate_repo_config: /tmp/WORKSPACE: multiple rules have the name "rules_pkg"
 and referenced by '//:kustomize'
ERROR: Analysis of target '//:kustomize' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.700s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 27 targets configured)
```

It appears possible to workaround this by telling bazel to do whatever its doing with a WORKSPACE that just includes the `rules_go` definitions. But since this is completely undocumented beyond one mention of redirecting to a `WORKSPACE.bazel` its unclear if this could cause any issues.

```
gazelle_dependencies(go_repository_default_config = "@//:WORKSPACE.gazelle")
```

**Comment by kurt-google** [comment]
Hmm ill close this out for now as trying to make a reproducer failed with a different more sensible error. I think there are some caching problems with the existing rule that lead to issue seen here that should be addressed.

The solution here was that my `WORKSPACE` was attempting to include `git_repository()` rules before calling `gazelle_dependencies()`, some how this didnt fail with gazelle being uninited but instead failed with claims about multiple rules being loaded.
