### ISSUE TITLE
Following README instructions fails

### ISSUE THREAD

**Issue by alokpr** [bazelbuild/bazel-gazelle#1366]
### What version of gazelle are you using?

0.28

### What version of rules_go are you using?

0.35

### What version of Bazel are you using?

5.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Ubuntu 18.04 x86-64

### What did you do?

Followed the README instructions exactly to setup gazelle

### What did you expect to see?

bazel run //:gazelle to run without error

### What did you see instead?

```
$ bazel run //:gazelle
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
	File "/home/alok/.cache/bazel/_bazel_alok/baa79780768e5783a41896090bd66734/external/bazel_gazelle/internal/BUILD.bazel", line 19, column 26, in <toplevel>
		gazelle_binary_test_suite()
	File "/home/alok/.cache/bazel/_bazel_alok/baa79780768e5783a41896090bd66734/external/bazel_gazelle/internal/gazelle_binary_test.bzl", line 27, column 19, in gazelle_binary_test_suite
		unittest.suite(
	File "/home/alok/.cache/bazel/_bazel_alok/baa79780768e5783a41896090bd66734/external/bazel_skylib/lib/unittest.bzl", line 270, column 18, in _suite
		test_rule(name = test_name)
Error: 'struct' object is not callable
ERROR: /home/alok/dexrobo/thirdparty/foxglove-schemas/BUILD.bazel:3:8: every rule of type _gazelle_runner implicitly depends upon the target '@bazel_gazelle//internal:gazelle.bash.in', but this target could not be found because of: no such target '@bazel_gazelle//internal:gazelle.bash.in': target 'gazelle.bash.in' not declared in package 'internal'; however, a source file of this name exists.  (Perhaps add 'exports_files(["gazelle.bash.in"])' to internal/BUILD?) defined by /home/alok/.cache/bazel/_bazel_alok/baa79780768e5783a41896090bd66734/external/bazel_gazelle/internal/BUILD.bazel

```

**Comment by alokpr** [comment]
I had a WORKSPACE rule to pull `@com_google_protobuf` and calling `protobuf_deps()` before `gazelle_dependencies()`. Moving `protobuf_deps()` after `gazelle_dependencies()` fixed this issue.

Ordering WORKSPACE rules is tricky with non-obvious error messages!
