### ISSUE TITLE
go_deps.from_file() fails to parse modules created with go 1.21

### ISSUE THREAD

**Issue by imeyer** [bazelbuild/bazel-gazelle#1625]
### What version of gazelle are you using?

0.32.0

### What version of rules_go are you using?

0.41.0

### What version of Bazel are you using?

6.3.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS 14.0beta7 / arm64

### What did you do?

[Using this repo as a starting point for a new project...](https://github.com/imeyer/gazelle-bug) I executed:

```
bazel run //:gazelle
```

### What did you expect to see?

```
~/code/gazelle-bug fixed > bazel run //:gazelle                                                                                                                    12:39:56
INFO: Analyzed target //:gazelle (18 packages loaded, 199 targets configured).
INFO: Found 1 target...
INFO: From GoLink external/gazelle~0.32.0/cmd/gazelle/gazelle_/gazelle [for tool]:
ld: warning: ignoring duplicate libraries: '-lm'
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 61.356s, Critical Path: 41.52s
INFO: 63 processes: 20 internal, 43 darwin-sandbox.
INFO: Build completed successfully, 63 total actions
INFO: Running command line: bazel-bin/gazelle
```

### What did you see instead?

```
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_imeyer/ab55560b08a5c10f7616c1b9d4af5a39/external/gazelle~0.32.0/internal/bzlmod/go_deps.bzl", line 184, column 88, in _go_deps_impl
		module_path, module_tags_from_go_mod, go_mod_replace_map = deps_from_go_mod(module_ctx, from_file_tag.go_mod)
	File "/private/var/tmp/_bazel_imeyer/ab55560b08a5c10f7616c1b9d4af5a39/external/gazelle~0.32.0/internal/bzlmod/go_mod.bzl", line 21, column 26, in deps_from_go_mod
		go_mod = parse_go_mod(go_mod_content, go_mod_path)
	File "/private/var/tmp/_bazel_imeyer/ab55560b08a5c10f7616c1b9d4af5a39/external/gazelle~0.32.0/internal/bzlmod/go_mod.bzl", line 101, column 18, in parse_go_mod
		major, minor = go.split(".")
Error: too many values to unpack (got 3, want 2)
ERROR: Analysis of target '//:gazelle' failed; build aborted: error evaluating module extension go_deps in @gazelle~0.32.0//:extensions.bzl
INFO: Elapsed time: 0.156s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
ERROR: Build failed. Not running target
```

### What's happening?

In go 1.21 the parsing of `go.mod` is now strict about versioning where writing `1.21.0` will **only** build with `1.21.0` (and not `1.21-rc1` etc). The `go_deps.from_file()` function can not parse  as it expects 2 values from the split, yet gets 3 in  modules `init` by go 1.21. I am pretty sure this is fixed by #1605, but thought I'd report anyway for others who may get bit by this before the change in #1605 lands.

**Comment by imeyer** [comment]
Confirm, fixed by the release of `0.33.0`. 🎉
