### ISSUE TITLE
gazelle 0.35.0 panics

### ISSUE THREAD

**Issue by vihangm** [bazelbuild/bazel-gazelle#1723]
### What version of gazelle are you using?
`v0.35.0`

### What version of rules_go are you using?
`v0.45.1`

### What version of Bazel are you using?
`v6.4.0`

### Does this issue reproduce with the latest releases of all the above?
Can't easily test with bazel 7 in my current setup but I imagine it would repro.

### What operating system and processor architecture are you using?
Linux, Ubuntu 22.04

### What did you do?
Ran gazelle fix

### What did you expect to see?
No panic

### What did you see instead?
A segfault
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3c pc=0x6de8a2]

goroutine 1 [running]:
github.com/bazelbuild/bazel-gazelle/resolve.(*resolveConfig).findOverride(0xc00031e1b0, {{0x2e85e7?, 0x2ea8f4?}, {0xc000637531?, 0xd?}}, {0x2e85e7, 0x2})
        external/gazelle~0.35.0/resolve/config.go:90 +0xeb
github.com/bazelbuild/bazel-gazelle/resolve.FindRuleWithOverride(0x25a000?, {{0x2e85e7?, 0xc000637531?}, {0xc000637531?, 0x40?}}, {0x2e85e7, 0x2})
        external/gazelle~0.35.0/resolve/config.go:35 +0xf9
github.com/bazelbuild/bazel-gazelle/language/go.ResolveGo(0xc000000480, 0x6dd365?, 0xc00207e960, {0xc000637531, 0x26}, {{0xc0003d2d71, 0x3}, {0xc00047c4f8, 0x13}, {0xc000637674, ...}, ...})
        external/gazelle~0.35.0/language/go/resolve.go:134 +0x2dd
github.com/bazelbuild/bazel-gazelle/language/go.(*goLang).Resolve.func1({0xc000637531?, 0xc002af4d38?})
        external/gazelle~0.35.0/language/go/resolve.go:80 +0x8a
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).Map.func1({0xc0008a2c80, 0x4, 0x2?})
        external/gazelle~0.35.0/rule/platform_strings.go:147 +0xca
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).MapSlice.func1(...)
        external/gazelle~0.35.0/rule/platform_strings.go:165
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).MapSlice(0xc002af5008, 0x7f7eefd5f108?)
        external/gazelle~0.35.0/rule/platform_strings.go:208 +0xec
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).Map(0x3c9300?, 0xc0006418f0?)
        external/gazelle~0.35.0/rule/platform_strings.go:155 +0x6f
github.com/bazelbuild/bazel-gazelle/language/go.(*goLang).Resolve(0x25b67f0, 0xc000000480, 0xc0001bc0a0, 0xc00207e960, 0xc000b14880, {0x2b17e0?, 0xc000d01cb0?}, {{0xc0003d2d71, 0x3}, {0xc00047c4f8, ...}, ...}
)
        external/gazelle~0.35.0/language/go/resolve.go:79 +0x26c
main.runFixUpdate({0xc00002e0da, 0x1a}, 0x7ffdb8019794?, {0xc0000240d0, 0x9, 0x9})
        external/gazelle~0.35.0/cmd/gazelle/fix-update.go:471 +0x1bfe
main.run({0xc00002e0da?, 0x1a?}, {0xc0000240c0?, 0xa?, 0xa?})
        external/gazelle~0.35.0/cmd/gazelle/gazelle.go:95 +0x1dd
main.main()
        external/gazelle~0.35.0/cmd/gazelle/gazelle.go:72 +0xf5
make: *** [Makefile:33: gazelle] Error 2
```

**Comment by vihangm** [comment]
Note that this occurs with no `# gazelle:resolve` directives in our project.
If I add a `# gazelle:resolve`, I get a different issue:

```
fatal error: concurrent map read and map write

goroutine 1 [running]:
github.com/bazelbuild/bazel-gazelle/resolve.(*resolveConfig).findOverride(0xc000706d20, {{0x2e85e7?, 0x2ea8f4?}, {0xc000287e31?, 0xd?}}, {0x2e85e7, 0x2})
        external/gazelle~0.35.0/resolve/config.go:90 +0xeb
github.com/bazelbuild/bazel-gazelle/resolve.FindRuleWithOverride(0x25a000?, {{0x2e85e7?, 0xc000287e31?}, {0xc000287e31?, 0x40?}}, {0x2e85e7, 0x2})
        external/gazelle~0.35.0/resolve/config.go:35 +0xf9
github.com/bazelbuild/bazel-gazelle/language/go.ResolveGo(0xc000001200, 0x6dd365?, 0xc001cec8c0, {0xc000287e31, 0x26}, {{0xc0003d2d71, 0x3}, {0xc0003cd9c8, 0x13}, {0xc000287f44, ...}, ...})
        external/gazelle~0.35.0/language/go/resolve.go:134 +0x2dd
github.com/bazelbuild/bazel-gazelle/language/go.(*goLang).Resolve.func1({0xc000287e31?, 0xc0023e6d38?})
        external/gazelle~0.35.0/language/go/resolve.go:80 +0x8a
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).Map.func1({0xc000959fc0, 0x4, 0x2?})
        external/gazelle~0.35.0/rule/platform_strings.go:147 +0xca
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).MapSlice.func1(...)
        external/gazelle~0.35.0/rule/platform_strings.go:165
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).MapSlice(0xc0023e7008, 0x7f269adcf618?)
        external/gazelle~0.35.0/rule/platform_strings.go:208 +0xec
github.com/bazelbuild/bazel-gazelle/rule.(*PlatformStrings).Map(0x3c9300?, 0xc0009ace70?)
        external/gazelle~0.35.0/rule/platform_strings.go:155 +0x6f
github.com/bazelbuild/bazel-gazelle/language/go.(*goLang).Resolve(0x25b67f0, 0xc000001200, 0xc0001bcd70, 0xc001cec8c0, 0xc0009af500, {0x2b17e0?, 0xc0009b6360?}, {{0xc0003d2d71, 0x3}, {0xc0003cd9c8, ...}, ...})
        external/gazelle~0.35.0/language/go/resolve.go:79 +0x26c
main.runFixUpdate({0xc00002e0da, 0x1a}, 0x7ffe61c2d794?, {0xc0000240d0, 0x9, 0x9})
        external/gazelle~0.35.0/cmd/gazelle/fix-update.go:471 +0x1bfe
main.run({0xc00002e0da?, 0x1a?}, {0xc0000240c0?, 0xa?, 0xa?})
        external/gazelle~0.35.0/cmd/gazelle/gazelle.go:95 +0x1dd
main.main()
        external/gazelle~0.35.0/cmd/gazelle/gazelle.go:72 +0xf5

goroutine 164 [select]:
os/exec.(*Cmd).watchCtx(0xc0003acc60, 0xc0000322a0)
        GOROOT/src/os/exec/exec.go:757 +0xb5
created by os/exec.(*Cmd).Start in goroutine 1
        GOROOT/src/os/exec/exec.go:743 +0x9c9
make: *** [Makefile:33: gazelle] Error 2
```

**Comment by fmeum** [comment]
Cc @tyler-french Could this be related to your recent performance improvements?

**Comment by vihangm** [comment]
aha, I think this is an issue with the rules_proto we are using and it's handling of overrides
https://github.com/stackb/rules_proto/blob/master/pkg/protoc/resolver.go#L336-L351 which no longer works given the map based overrides

**Comment by vihangm** [comment]
This patch seems to fix it. https://github.com/stackb/rules_proto/pull/357
