### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by jbedard** [bazelbuild/bazel-gazelle#1751]
I assume this is a result of https://github.com/bazelbuild/bazel-gazelle/commit/073699ea1342b90ed0ca28ab39c90bc71c223e9a although I haven't investigated yet. Downgrading to 0.34 seems to work.

### What version of gazelle are you using?

0.35

### What version of rules_go are you using?

0.45.1

### What version of Bazel are you using?

6.5.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux 5.15.0-1017-aws x86_64

### What did you do?

```
bazel run //:gazelle
```

With a standard `gazelle_binary` + `gazelle` target.

### What did you expect to see?

Success

### What did you see instead?

Crash:

```
fatal error: concurrent map read and map write

goroutine 1 [running]:
github.com/bazelbuild/bazel-gazelle/resolve.(*resolveConfig).findOverride(0xc0008e8120, {{0x9eb3c4?, 0x9ed903?}, {0xc00109bec0?, 0xc00064fef0?}}, {0x9eb3c4, 0x2})
	external/bazel_gazelle/resolve/config.go:90 +0xf7
github.com/bazelbuild/bazel-gazelle/resolve.FindRuleWithOverride(0xc003a31940?, {{0x9eb3c4?, 0x4?}, {0xc00109bec0?, 0x947680?}}, {0x9eb3c4, 0x2})
	external/bazel_gazelle/resolve/config.go:35 +0x109
github.com/bazelbuild/rules_python/gazelle/python.(*Resolver).Resolve(0xc000d1e700?, 0xc0016e3200, 0xc0000e5060?, 0x40dea7?, 0xc002f68280, {0x9d8220, 0xc001cc6858}, {{0xc0002720a1, 0x5}, {0xc000531380, ...}, ...})
	external/rules_python_gazelle_plugin/python/resolve.go:173 +0xa2a
main.inverseMapKindResolver.Resolve({{0xc00173e063?, 0xc000189980?}, {0x7f2ab4af05e8?, 0xc000189980?}}, 0xc00173e06e?, 0xa?, 0xc00173e079?, 0xc0019f2000, {0x9d8220, 0xc001cc6858}, ...)
	external/bazel_gazelle/cmd/gazelle/metaresolver.go:98 +0x1c4
main.runFixUpdate({0xc00002807a, 0x14}, 0x7ffc61a05478?, {0xc00018a010, 0x0, 0x0})
	external/bazel_gazelle/cmd/gazelle/fix-update.go:471 +0x1b77
main.run({0xc00002807a?, 0x14?}, {0xc00018a010?, 0x1?, 0x1?})
	external/bazel_gazelle/cmd/gazelle/gazelle.go:95 +0x1e8
main.main()
	external/bazel_gazelle/cmd/gazelle/gazelle.go:72 +0xd9

goroutine 7 [select]:
os/exec.(*Cmd).watchCtx(0xc0007f7600, 0xc000100120)
	GOROOT/src/os/exec/exec.go:757 +0xc5
created by os/exec.(*Cmd).Start
	GOROOT/src/os/exec/exec.go:743 +0x9f3
```

**Comment by fmeum** [comment]
@tyler-french Didn't we fix an issue like that?

**Comment by vihangm** [comment]
See #1723
If you are using gazelle and stackb/rules_proto, the upgrade to gazelle 0.35.0 and rules_proto v3 need to be done in lock step.

**Comment by jbedard** [comment]
Yeah there's a very good chance that was the issue. Feel free to close this if you think that's correct.
