### ISSUE TITLE
bzlmod/go_deps: bazel mod tidy adds repos that are loaded as bazel modules

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel-gazelle#1935]
To reproduce:

MODULE.bazel
```
bazel_dep(name = "flatbuffers", version = "24.3.25", repo_name = "com_github_google_flatbuffers")
```
go.mod (includes direct dep)
```
	github.com/google/flatbuffers v2.0.8+incompatible
```
`bazel mod tidy`:
```
ported incorrect imports of repositories via use_repo():

Not imported, but reported as direct dependencies by the extension (may cause the build to fail):
    com_github_google_flatbuffers

Fix the use_repo calls by running 'bazel mod tidy'.
INFO: Updated use_repo calls for @bazel_gazelle//:extensions.bzl%go_deps
```
Build failure caused:
```
tfrench@go(tfrench.devpod-us-va) ~/go-code
 % bazel mod --enable_bzlmod tidy
INFO: Invocation ID: ff5667e5-9cef-425c-b978-77434bfebe7d
ERROR: Traceback (most recent call last):
        File "/home/user/go-code/MODULE.bazel", line 209, column 8, in <toplevel>
                include("//third_party:go_deps.MODULE.bazel")
        File "<builtin>", in include
        File "/home/user/go-code/third_party/go_deps.MODULE.bazel", line 17, column 9, in <toplevel>
                use_repo(
Error in use_repo: The repo name 'com_github_google_flatbuffers' is already being used by a bazel_dep at /home/user/go-code/MODULE.bazel:40:10
ERROR: error executing MODULE.bazel file for <root>. Type 'bazel help mod' for syntax and help.
```

**Comment by fmeum** [comment]
In Bazel 7.4.0 and 8, you will be able to have `go_deps` reuse the `bazel_dep` via `override_repo`. I will add a test case to verify that `bazel mod tidy` behaves correctly in that case.

**Comment by tyler-french** [comment]
I wonder if for now we can just look at all the `repo_name` of the `bazel_dep` in the root MODULE.bazel, and then skip adding these to direct dependencies?

**Comment by fmeum** [comment]
The Gazelle extension can't do this as it doesn't have access to MODULE files.

Having looked into this more, I think that it's actually a feature (but not with a good error message): You have the same dep show up under two different names in your dep tree, which can result in linker errors. Instead, when Bazel 7.4.0 lands, you should use `override_repo` to replace the extension repo with the Bazel dep.

**Comment by AlejoAsd** [comment]
I am facing a similar problem, but the project I am working on uses Bazel `7.0.2`, and this is something I don't have control over.

Is there a way to manually tell Gazelle not to manage a specific dependency in older Bazel versions that don't have `override_repo`?

**Comment by fmeum** [comment]
Could you rename the conflicting dep via the `repo_name` attribute of `bazel_dep`? We can add a new knob, I would just like to make sure it's the right one and actually needed.

**Comment by rajukrishnamurthy** [comment]
@AlejoAsd fwiw, I ran into this same issue and was able to resolve it without overrides etc.,  I am using bazel `7.6.1` and gazelle `0.40.0`, so I don't know if the handling is different.  `bazel mod tidy` will add to use_repo from go.mod if 

1. it's a direct dependency
2. the repo, with the same version, doesn't already exist.

I have:
```
bazel_dep(name = "grpc_ecosystem_grpc_gateway", version = "2.26.3", repo_name = "com_github_grpc_ecosystem_grpc_gateway_v2")
```

but the version in go.mod was different.  I manually removed `com_github_grpc_ecosystem_grpc_gateway_v2` from `use_repo`, go got version 2.26.3 and reran `go mod tidy && bazel mod tidy` (you might want to also `bazel clean --expunge && rm go.sum && rm MODULE.bazel.lock` but not sure it's necessary)

this does mean that you have to keep the versions in sync.
