### ISSUE TITLE
gazelle_binary: Custom language implementation results in "flag redefined"

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#396]
I'm trying to use the new custom language to implement the scenario I described in #388, but I'm having trouble running gazelle with a custom language implementation at all. 

You can reproduce by cloning:
https://github.com/robfig/gazelle-language-test

and run:
bazel run :gazelle -- gocode/

I see this panic, only when the custom language is included in the gazelle_binary:
```
gazelle flag redefined: repo_root
panic: gazelle flag redefined: repo_root

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000b8b40, 0x15c5220, 0xc0000cc820, 0x149f6a4, 0x9, 0x14bdd61, 0x56)
	GOROOT/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc0000b8b40, 0xc0000cc820, 0x149f6a4, 0x9, 0x0, 0x0, 0x14bdd61, 0x56)
	GOROOT/src/flag/flag.go:708 +0x8a
github.com/bazelbuild/bazel-gazelle/config.(*CommonConfigurer).RegisterFlags(0xc0000cc820, 0xc0000b8b40, 0x149e4e5, 0x6, 0xc0001a1ab0)
	external/bazel_gazelle/config/config.go:158 +0x6d
main.newFixUpdateConfiguration(0x0, 0xc0000ba010, 0x1, 0x1, 0xc0000ec0c0, 0x7, 0xc, 0xc0000ea600, 0x4, 0x4, ...)
	external/bazel_gazelle/cmd/gazelle/fix-update.go:299 +0x214
main.runFixUpdate(0x0, 0xc0000ba010, 0x1, 0x1, 0x189c420, 0x1132d00)
	external/bazel_gazelle/cmd/gazelle/fix-update.go:180 +0x804
main.run(0xc0000ba010, 0x1, 0x1, 0xc0000cc820, 0x14a0c18)
	external/bazel_gazelle/cmd/gazelle/gazelle.go:78 +0x158
main.main()
	external/bazel_gazelle/cmd/gazelle/gazelle.go:59 +0x91
```

It sounds like there are multiple copies of gazelle in the compilation, but I'm not sure how that happens. The custom language uses an external reference to gazelle, not a vendored copy:

```
go_library(
    name = "go_default_library",
    srcs = [
        "lang.go",
        "resolve.go",
    ],
    importpath = "alpha/customlang",
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_gazelle//config:go_default_library",
        "@bazel_gazelle//label:go_default_library",
        "@bazel_gazelle//language:go_default_library",
        "@bazel_gazelle//repo:go_default_library",
        "@bazel_gazelle//resolve:go_default_library",
        "@bazel_gazelle//rule:go_default_library",
    ],
)
```

Thank you!

**Comment by robfig** [comment]
Doh, looking at it with fresh eyes it's obvious that this is because I'm reusing config.CommonConfigurer to satisfy the Configurer interface requirement, and it's not meant to be reused. Upon replacing it with a stub implementation instead, this now no longer crashes. Sorry for the false alarm.
