### ISSUE TITLE
read_cache_env fails on windows

### ISSUE THREAD

**Issue by Chronojam** [bazelbuild/bazel-gazelle#594]
Hiya, hopefully not a duplicate, but couldnt find anything related.

Given the following:

```
# *snip*

http_archive(
    name = "io_bazel_rules_go",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/0.19.1/rules_go-0.19.1.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/0.19.1/rules_go-0.19.1.tar.gz",
    ],
    sha256 = "8df59f11fb697743cbb3f26cfb8750395f30471e9eabde0d174c3aebc7a1cd39",
)
http_archive(
    name = "bazel_gazelle",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/0.18.1/bazel-gazelle-0.18.1.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/0.18.1/bazel-gazelle-0.18.1.tar.gz",
    ],
    sha256 = "be9296bfd64882e3c08e3283c58fcb461fa6dd3c171764fcc4cf322f60615a9b",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()
go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

# go_repository rules
```

I can not run gazelle due to the follow error:

```
> bazel run //:gazelle -- --help
*snip*
ERROR: An error occurred during the fetch of repository 'com_github_pelletier_go_toml':
   Traceback (most recent call last):
        File "C:/users/calli/_bazel_calli/ccxye3xt/external/bazel_gazelle/internal/go_repository.bzl", line 98
                read_cache_env(ctx, str(ctx.path(Label("@bazel_ga..."))))
        File "C:/users/calli/_bazel_calli/ccxye3xt/external/bazel_gazelle/internal/go_repository_cache.bzl", line 81, in read_cache_env
                fail(("failed to read cache environme...))
failed to read cache environment: java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("cat" C:/users/calli/_bazel_calli/ccxye3xt/external/bazel_gazelle_go_repository_cache/go.env): The system cannot find the file specified.

*snip; more of the same errors below*
```

(the above runs without issue on linux)

At first i had thought that the @bazel_gazelle_go_repository_cache//:go.env file/target didnt exist, but ive verified that its both in the location listed, and within external/bazel_gazelle_go_respository_cache/go.env

Any pointers? 
Thanks!

**Comment by Chronojam** [comment]
Hi, sorry about this - but after a ``` bazel clean --expunge ``` this seems to have fixed itself. 
Thanks

**Comment by crazyStrongboy** [comment]
> Hi, sorry about this - but after a `bazel clean --expunge` this seems to have fixed itself.
> Thanks

I have the same problem. Why does it happen？

**Comment by lightecoder** [comment]
After running command 
`bazel run //:gazelle`
 in cmd.exe I had the same error.
 All I need to do was run again to clear:
`bazel clean --expunge`
Than I opened bash terminal and run again command :
`bazel run //:gazelle` 
It seams that in Windows environment we should use only bash terminal.
