### ISSUE TITLE
Error in rule: 'rule' can only be called during the loading phase

### ISSUE THREAD

**Issue by hugelgupf** [bazelbuild/bazel-gazelle#899]
### What version of gazelle are you using?

copied the lasted from README: 0.22.0

### What version of rules_go are you using?

latest from README: 0.24.1

### What version of Bazel are you using?

Build label: 3.5.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

gLinux

### What did you do?

copy & pasted the WORKSPACE from the readme:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "7f1aa43d986df189f7cf30e81dd2dc9d8ed7c74e356341a17267f6d7e5748382",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.1/rules_go-v0.24.1.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.1/rules_go-v0.24.1.tar.gz",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "d4113967ab451dd4d2d767c3ca5f927fec4b30f3b2c6f8135a2033b9c05a5687",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.0/bazel-gazelle-v0.22.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.0/bazel-gazelle-v0.22.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

go_rules_dependencies()

go_register_toolchains()

gazelle_dependencies()

load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(
    name = "gazelle",
    prefix = "github.com/u-root/gobusybox/src",
)
```

Then, I ran

```
bazel run //:gazelle
```

### What did you expect to see?

BUILD.bazel rule files

### What did you see instead?

```
ERROR: Traceback (most recent call last):
        File "/usr/local/google/home/chrisko/go/src/github.com/u-root/gobusybox/src/WORKSPACE", line 32, column 8, in <toplevel>
                gazelle(
        File "/usr/local/google/home/chrisko/.cache/bazel/_bazel_chrisko/b7d27532b9fdb212f1847e2c81d5c56a/external/bazel_gazelle/def.bzl", line 127, column 20, in gazelle
                _gazelle_runner(
Error in rule: 'rule' can only be called during the loading phase
ERROR: error loading package 'external': Package 'external' contains errors
```

**Comment by hugelgupf** [comment]
Hah, I'm so sorry.

I put the gazelle() rule in WORKSPACE, not in BUILD. My bad.
